### ISSUE TITLE
Big Cleanup for v1

### ISSUE THREAD

**Issue by iejMac** [iejMac/video2dataset#201]
I'd like to do a big cleanup and release v1. Here are the TODO's for that:

- [x] Improve parameter docs, one big list just feels strange, some of the items are dicts, maybe yaml + OmegaConf is better, define some default configs you can choose between and if you need fine grained control you can make your own config based on info in the Subsampler/Worker docs
- [x] Clean up README - maybe make new diagram (https://github.com/iejMac/video2dataset/issues/207)
- [x] https://github.com/iejMac/video2dataset/issues/195
- [x] Maybe simplify dataloader but keep in in case stable-datasets doesn't work
- [x] Clean up dataset examples, update them to show what we did exactly + add benchmark numbers from those runs/cost
- [x] Add to README some nice benchmark numbers like how long it would take to download WebVid on one machine using multiprocessing and cost
- [x] Add re-processing example (cut detection -> clipping -> optical flow) draw the tree (maybe diagram)
- [x] Add W&B integration
- [x] Add more complex usage examples (our paper, other video papers) + add generative samples etc.
- [x] Try to fix spark distribution
- [ ] Try to write the paper and add it (non-blocking imo)
- [ ] UNIFY WORKERS - there should one worker (https://github.com/iejMac/video2dataset/issues/206)
- [ ] Update package (https://github.com/iejMac/video2dataset/issues/176, maybe fix this)
